server: 
  port: 9000
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ZIPKIN-SERVER-9000
    prefer-ip-address: true     #访问路径可以显示IP地址

endpoints:
  env:
    sensitive: false  #关闭environment的检查，前段可以直接访问

spring:
  cloud:
    config:
      allow-override: true
  application:
    name: zipkin-server

 